/**
 * Caption Export Utility for ClassBridge
 * Supports dual-format exports:
 * 1. Plain Text (.txt) formatted transcript with timestamps, bilingual pairs, and STEM terms
 * 2. Publication-grade Academic PDF (.pdf) with resilient fallback for native Indic font rendering
 */

const LANGUAGE_NAMES = {
  en: { name: 'English', native: 'English' },
  ta: { name: 'Tamil', native: 'தமிழ்' },
  ml: { name: 'Malayalam', native: 'മലയാളം' },
  hi: { name: 'Hindi', native: 'हिन्दी' },
};

/**
 * Clean and format timestamp string
 */
function formatSegmentTime(seg, index) {
  if (seg.timestamp) return seg.timestamp;
  if (typeof seg.start === 'number' && typeof seg.end === 'number') {
    const fmt = (s) => {
      const m = Math.floor(s / 60).toString().padStart(2, '0');
      const sec = Math.floor(s % 60).toString().padStart(2, '0');
      return `${m}:${sec}`;
    };
    return `${fmt(seg.start)} - ${fmt(seg.end)}`;
  }
  const s = index * 5;
  const m1 = Math.floor(s / 60).toString().padStart(2, '0');
  const s1 = (s % 60).toString().padStart(2, '0');
  const m2 = Math.floor((s + 5) / 60).toString().padStart(2, '0');
  const s2 = ((s + 5) % 60).toString().padStart(2, '0');
  return `${m1}:${s1} - ${m2}:${s2}`;
}

/**
 * 1. Export captions as a clean, structured Plain Text (.txt) file
 */
export function exportCaptionsAsTxt(segments = [], sourceLang = 'en', targetLang = 'ta') {
  if (!segments || segments.length === 0) {
    alert("No caption segments recorded yet to export.");
    return false;
  }

  const srcMeta = LANGUAGE_NAMES[sourceLang] || { name: sourceLang.toUpperCase(), native: sourceLang.toUpperCase() };
  const tgtMeta = LANGUAGE_NAMES[targetLang] || { name: targetLang.toUpperCase(), native: targetLang.toUpperCase() };
  const now = new Date();
  const dateFormatted = now.toLocaleString();

  let avgConf = 0;
  if (segments.length > 0) {
    const total = segments.reduce((acc, s) => acc + (s.confidence || 95), 0);
    avgConf = Math.round(total / segments.length);
  }

  const header = [
    "================================================================================",
    "CLASSBRIDGE — LIVE BILINGUAL LECTURE TRANSCRIPT",
    "================================================================================",
    `Session Date:       ${dateFormatted}`,
    `Language Direction: [${sourceLang.toUpperCase()}] ${srcMeta.name} <-> [${targetLang.toUpperCase()}] ${tgtMeta.name} (${tgtMeta.native})`,
    `Total Segments:     ${segments.length}`,
    `Average Confidence: ${avgConf}%`,
    "Platform:           ClassBridge — Real-Time Indic STEM Lecture Companion",
    "================================================================================",
    "",
    "--- TRANSCRIPT LOG ---",
    ""
  ].join("\n");

  const body = segments.map((seg, idx) => {
    const time = formatSegmentTime(seg, idx);
    const conf = Math.round(seg.confidence || 95);
    const srcText = seg.text_source || seg.text_en || "";
    const tgtText = seg.text_vernacular || "";
    
    let termsStr = "";
    if (seg.domain_terms && seg.domain_terms.length > 0) {
      const termsList = seg.domain_terms.map(t => {
        const trans = t.translations && t.translations[targetLang] ? ` (${t.translations[targetLang]})` : "";
        return `${t.en || t.term}${trans}`;
      }).join(", ");
      termsStr = `\nSTEM Terms: ${termsList}`;
    }

    return [
      `[#${idx + 1} | ${time} | Confidence: ${conf}%]`,
      `${sourceLang.toUpperCase()}: ${srcText}`,
      `${targetLang.toUpperCase()}: ${tgtText}${termsStr}`,
      "--------------------------------------------------------------------------------"
    ].join("\n");
  }).join("\n\n");

  const footer = [
    "",
    "================================================================================",
    `End of Transcript (${segments.length} segments exported)`,
    "Generated by ClassBridge AI (TENSORA 2026)",
    "================================================================================"
  ].join("\n");

  const fullText = `${header}\n${body}\n${footer}`;
  const blob = new Blob([fullText], { type: "text/plain;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  const filenameDate = now.toISOString().slice(0, 10);
  a.href = url;
  a.download = `ClassBridge_Lecture_Transcript_${sourceLang.toUpperCase()}_to_${targetLang.toUpperCase()}_${filenameDate}.txt`;
  document.body.appendChild(a);
  a.click();
  a.remove();
  URL.revokeObjectURL(url);
  return true;
}

/**
 * 2. Export captions as a styled, academic PDF document
 * Attempts backend API generation first; if offline or fails, falls back
 * immediately to a high-fidelity client-side printable PDF document with
 * full Unicode Indic typography (Tamil, Malayalam, Hindi) support.
 */
export async function exportCaptionsAsPdf(segments = [], sourceLang = 'en', targetLang = 'ta', apiBaseUrl = '') {
  if (!segments || segments.length === 0) {
    alert("No caption segments recorded yet to export.");
    return false;
  }

  const srcMeta = LANGUAGE_NAMES[sourceLang] || { name: sourceLang.toUpperCase(), native: sourceLang.toUpperCase() };
  const tgtMeta = LANGUAGE_NAMES[targetLang] || { name: targetLang.toUpperCase(), native: targetLang.toUpperCase() };
  const filenameDate = new Date().toISOString().slice(0, 10);
  const downloadName = `ClassBridge_Lecture_Captions_${sourceLang.toUpperCase()}_to_${targetLang.toUpperCase()}_${filenameDate}.pdf`;

  // First try backend PDF export if backend is available
  try {
    const res = await fetch(`${apiBaseUrl}/api/captions/pdf`, {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        segments,
        source_lang: sourceLang,
        target_lang: targetLang,
        title: `ClassBridge Live Lecture Bilingual Captions (${srcMeta.name} to ${tgtMeta.name})`
      }),
      signal: AbortSignal.timeout(4000)
    });

    if (res.ok) {
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = downloadName;
      document.body.appendChild(a);
      a.click();
      a.remove();
      URL.revokeObjectURL(url);
      return true;
    }
  } catch (err) {
    console.info("Backend PDF endpoint unavailable, using native client-side printable PDF renderer...", err);
  }

  // Resilient High-Fidelity Printable PDF Fallback
  // Leverages the browser's native OS Indic text shaping engine (Noto Sans Tamil/Malayalam/Devanagari, Nirmala UI)
  return printCaptionsAsPdfDocument(segments, sourceLang, targetLang, srcMeta, tgtMeta);
}

/**
 * Client-Side Printable PDF Renderer
 * Formats a clean, publication-ready academic document and triggers print/save as PDF.
 */
function printCaptionsAsPdfDocument(segments, sourceLang, targetLang, srcMeta, tgtMeta) {
  const printWindow = window.open('', '_blank', 'width=960,height=800');
  if (!printWindow) {
    alert("Please allow popups for this site to export PDF.");
    return false;
  }

  const now = new Date();
  const dateFormatted = now.toLocaleString();
  const total = segments.reduce((acc, s) => acc + (s.confidence || 95), 0);
  const avgConf = Math.round(total / (segments.length || 1));

  const rowsHtml = segments.map((seg, idx) => {
    const time = formatSegmentTime(seg, idx);
    const conf = Math.round(seg.confidence || 95);
    const srcText = seg.text_source || seg.text_en || "";
    const tgtText = seg.text_vernacular || "";

    const termsBadges = (seg.domain_terms || []).map(t => {
      const trans = t.translations && t.translations[targetLang] ? ` (${t.translations[targetLang]})` : "";
      return `<span class="term-badge">🔬 ${t.en || t.term}${trans}</span>`;
    }).join(" ");

    return `
      <div class="caption-row">
        <div class="row-meta">
          <span class="seg-num">#${idx + 1}</span>
          <span class="seg-time">⏱️ ${time}</span>
          <span class="seg-conf">🎯 ${conf}% Confidence</span>
        </div>
        <div class="lang-block src-block">
          <span class="lang-tag">${sourceLang.toUpperCase()}</span>
          <div class="lang-text">${escapeHtml(srcText)}</div>
        </div>
        <div class="lang-block tgt-block">
          <span class="lang-tag tgt-tag">${targetLang.toUpperCase()}</span>
          <div class="lang-text tgt-text">${escapeHtml(tgtText)}</div>
        </div>
        ${termsBadges ? `<div class="terms-row">${termsBadges}</div>` : ''}
      </div>
    `;
  }).join("");

  function escapeHtml(str) {
    return (str || '').replace(/[&<>"']/g, (m) => ({
      '&': '&amp;',
      '<': '&lt;',
      '>': '&gt;',
      '"': '&quot;',
      "'": '&#039;'
    }[m]));
  }

  const html = `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="utf-8">
      <title>ClassBridge Lecture Captions — ${srcMeta.name} to ${tgtMeta.name}</title>
      <style>
        @page {
          size: A4;
          margin: 15mm;
        }
        * {
          box-sizing: border-box;
          margin: 0;
          padding: 0;
        }
        body {
          font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Noto Sans Tamil", "Noto Sans Malayalam", "Noto Sans Devanagari", "Nirmala UI", sans-serif;
          color: #0f172a;
          background: #ffffff;
          line-height: 1.5;
          padding: 24px;
        }
        .header {
          border-bottom: 2px solid #2563eb;
          padding-bottom: 14px;
          margin-bottom: 18px;
        }
        .title-row {
          display: flex;
          align-items: center;
          justify-content: space-between;
        }
        .title {
          font-size: 20px;
          font-weight: 800;
          color: #1e3a8a;
          display: flex;
          align-items: center;
          gap: 8px;
        }
        .meta-grid {
          display: grid;
          grid-template-columns: repeat(auto-fit, minmax(180px, 1fr));
          gap: 8px;
          margin-top: 10px;
          font-size: 11px;
          color: #475569;
          background: #f8fafc;
          padding: 10px 14px;
          border-radius: 6px;
          border: 1px solid #e2e8f0;
        }
        .meta-item b {
          color: #0f172a;
        }
        .caption-list {
          display: flex;
          flex-direction: column;
          gap: 12px;
        }
        .caption-row {
          border: 1px solid #e2e8f0;
          border-radius: 8px;
          padding: 12px 14px;
          background: #ffffff;
          page-break-inside: avoid;
        }
        .row-meta {
          display: flex;
          align-items: center;
          gap: 12px;
          font-size: 11px;
          font-weight: 700;
          margin-bottom: 8px;
          color: #64748b;
        }
        .seg-num {
          background: #e2e8f0;
          color: #1e293b;
          padding: 2px 7px;
          border-radius: 4px;
        }
        .seg-time {
          color: #0284c7;
        }
        .seg-conf {
          color: #059669;
          margin-left: auto;
        }
        .lang-block {
          display: flex;
          align-items: baseline;
          gap: 10px;
          margin-bottom: 6px;
        }
        .lang-tag {
          font-size: 10px;
          font-weight: 800;
          background: #eff6ff;
          color: #2563eb;
          border: 1px solid #bfdbfe;
          padding: 1px 6px;
          border-radius: 4px;
          flex-shrink: 0;
        }
        .tgt-tag {
          background: #ecfdf5;
          color: #059669;
          border-color: #a7f3d0;
        }
        .lang-text {
          font-size: 12.5px;
          color: #1e293b;
          line-height: 1.45;
        }
        .tgt-text {
          color: #047857;
          font-weight: 600;
        }
        .terms-row {
          display: flex;
          flex-wrap: wrap;
          gap: 6px;
          margin-top: 6px;
          padding-top: 6px;
          border-top: 1px dashed #f1f5f9;
        }
        .term-badge {
          font-size: 10px;
          background: #f0fdf4;
          color: #15803d;
          border: 1px solid #bbf7d0;
          padding: 2px 6px;
          border-radius: 4px;
        }
        .footer {
          margin-top: 24px;
          padding-top: 12px;
          border-top: 1px solid #e2e8f0;
          text-align: center;
          font-size: 11px;
          color: #94a3b8;
        }
        .print-btn-banner {
          background: #eff6ff;
          border: 1px solid #bfdbfe;
          padding: 10px 14px;
          margin-bottom: 16px;
          border-radius: 6px;
          display: flex;
          align-items: center;
          justify-content: space-between;
          font-size: 12px;
          color: #1e40af;
        }
        .btn-print {
          background: #2563eb;
          color: #ffffff;
          border: none;
          padding: 6px 14px;
          border-radius: 4px;
          font-weight: 700;
          cursor: pointer;
        }
        @media print {
          .print-btn-banner {
            display: none !important;
          }
          body {
            padding: 0;
          }
        }
      </style>
    </head>
    <body>
      <div class="print-btn-banner">
        <span>📄 Click <b>Save as PDF</b> in your print dialogue to save this document.</span>
        <button class="btn-print" onclick="window.print()">Print / Save as PDF</button>
      </div>

      <div class="header">
        <div class="title-row">
          <div class="title">🎓 ClassBridge — Live Bilingual Lecture Captions</div>
        </div>
        <div class="meta-grid">
          <div class="meta-item"><b>Session Date:</b> ${dateFormatted}</div>
          <div class="meta-item"><b>Direction:</b> ${sourceLang.toUpperCase()} (${srcMeta.name}) ➔ ${targetLang.toUpperCase()} (${tgtMeta.name})</div>
          <div class="meta-item"><b>Captions:</b> ${segments.length} Segments</div>
          <div class="meta-item"><b>Avg Confidence:</b> ${avgConf}%</div>
        </div>
      </div>

      <div class="caption-list">
        ${rowsHtml}
      </div>

      <div class="footer">
        ClassBridge — Real-Time Vernacular Lecture Companion | TENSORA 2026 Grounded AI Synthesis
      </div>

      <script>
        window.addEventListener('load', () => {
          setTimeout(() => {
            window.print();
          }, 300);
        });
      </script>
    </body>
    </html>
  `;

  printWindow.document.open();
  printWindow.document.write(html);
  printWindow.document.close();
  return true;
}
